import {emptyState,applyAction} from './engine.js';
const app=document.querySelector('#app'),cfg=window.STUDY_CONFIG;
const KEY='alexey-tcp-practice-v1',TOKEN='alexey-tcp-access-v1';
let bank,state,token='',demo=false,screen='home',busy=false,error='',synced=false,query='',filter='all';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>bank.cards.find(c=>c.id===id),topicName=id=>bank.topics.find(t=>t.id===id)?.title||'';
const level=id=>state?.levels[id]?.level||0;
const mastered=()=>bank.cards.filter(c=>level(c.id)===3).length;
const active=()=>state?.session&&!state.session.finished;
const observer=()=>state?.role==='observer';
const levelNames=['На повторении','Первое подтверждение','Закрепляется','Освоено'];
const date=t=>t?new Date(t).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Пока нет';
function button(action,text,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${busy?'disabled':''} ${extra}>${text}</button>`;}
function progress(n,total,label){return `<div class="progress" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${n}"><span style="width:${total?n/total*100:0}%"></span></div>`;}
function shell(content){const role=demo?'Пробный режим':observer()?'Просмотр наставника':'Подготовка Алексея';return `<div class="shell"><aside class="side"><a class="brand" href="#" data-action="home">Сетевой калькулятор<small>Подготовка к защите</small></a><nav aria-label="Разделы">${[['home','Подготовка'],['library','Все вопросы'],['stats','Прогресс'],['rules','Как заниматься']].map(([id,t])=>`<button data-action="${id}" ${screen===id?'aria-current="page"':''}>${t}</button>`).join('')}</nav><div class="side-bottom"><strong>TCP · poll · C++</strong><p>Теория, конкретный код и объяснение своими словами.</p><a href="presentation.html">Презентация для созвона</a><p>${esc(role)}</p></div></aside><div class="main-wrap"><header class="top"><div class="sync" data-kind="${error?'error':synced?'ok':'info'}" role="status">${busy?'Сохраняем ответ…':error?'Есть проблема с сохранением':demo?'Пробный прогресс: только этот браузер':synced?'Общий прогресс сохранен':'Подключаем общее сохранение…'}<span>${!demo&&state?.updatedAt?'· '+date(state.updatedAt):''}</span></div>${button('logout',demo?'Войти':'Выйти','quiet')}</header><main id="main" class="main">${error?`<div class="notice error" role="alert"><p>${esc(error)}</p>${button('refresh','Обновить состояние','quiet')}</div>`:''}${content}</main></div></div>`;}
function home(){const n=mastered(),seen=Object.keys(state.levels).length,wrong=bank.cards.filter(c=>state.levels[c.id]&&level(c.id)<3&&state.levels[c.id].wrong).length;return `<div class="intro"><h1>Разобраться в коде.<br>Уверенно объяснить.</h1><p>Подготовка к защите сетевого калькулятора: один вопрос, точное объяснение и связь с исходниками.</p></div>${demo?'<div class="notice info"><p>Это отдельная пробная попытка. Ее ответы не попадут в общий прогресс Алексея.</p></div>':''}<div class="stats-line"><span><strong>${n}/${bank.cards.length}</strong> освоено</span><span><strong>${seen}</strong> встречалось</span><span><strong>${wrong}</strong> с ошибками</span></div>${progress(n,bank.cards.length,'Освоено вопросов')}<section class="study-start"><div><h2>${active()?'Продолжить начатое':'Следующий подход'}</h2><p>${active()?`Отвечено ${Object.keys(state.session.answers).length} из ${state.session.deck.length}. Можно продолжить с любого устройства.`:'До 15 вопросов. Новые темы и 3-5 повторений, когда есть что повторять.'}</p></div><div class="actions">${observer()?'<span class="muted">Режим просмотра</span>':active()?button('resume','Продолжить','primary'):button('start','Начать подход','primary')}</div></section><div class="program-head"><h2>Темы подготовки</h2><p class="small muted">Три подтверждения в разных подходах</p></div><section class="topic-list" aria-label="Темы">${bank.topics.map(t=>{let all=bank.cards.filter(c=>c.topic===t.id),done=all.filter(c=>level(c.id)===3).length;return `<article class="topic-row"><div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p></div><div class="topic-right"><span>${done} / ${all.length}</span>${button('topic','Открыть','',`data-topic="${t.id}" ${active()||observer()?'disabled':''}`)}</div></article>`;}).join('')}</section><section class="study-start"><div><h2>Общий тест</h2><p>${n===bank.cards.length?'Все темы освоены. Полный тест без подсказок готов.':`Откроется после освоения всех ${bank.cards.length} вопросов. Осталось ${bank.cards.length-n}.`}</p></div>${button('final','Начать тест','',`${n<bank.cards.length||active()||observer()?'disabled':''}`)}</section><a class="document-link" href="presentation.html">Открыть презентацию и объяснения для созвона</a>`;}
function code(c){const e=bank.evidence[c.evidence];return `<details class="code-details"><summary>Посмотреть в коде: ${esc(e.file)}</summary><p class="small muted">Строки ${e.start}-${e.end} исходного проекта. Это код присланной версии.</p><pre><code>${esc(e.code.split('\n').map((l,i)=>`${e.start+i}  ${l}`).join('\n'))}</code></pre></details>`;}
function feedback(c,a,withLevel=true){const good=a?.correct;const last=[...state.history].reverse().find(h=>h.card===c.id);return `<section class="feedback ${good?'good':'bad'}"><h2>${a?(good?'Верно':'Разберем ошибку'):'Объяснение'}</h2><p><strong>${esc(c.answer)}</strong></p><p>${esc(c.explanation)}</p>${a&&!good?`<p>Вы выбрали: ${esc(c.options[a.choice]?.text)}<br>${esc(c.options[a.choice]?.explanation)}</p>`:''}${withLevel&&last?`<p class="level-change">Уровень: ${last.before} из 3 → ${last.after} из 3. ${good?(last.after===3?'Вопрос освоен.':'Верные ответы в новых подходах повысят уровень до 3.'):'Вопрос вернулся на повторение.'}</p>`:''}${code(c)}<details class="wrong-detail"><summary>Почему другие варианты не подходят</summary>${c.options.filter(o=>!o.correct).map(o=>`<p><strong>${esc(o.text)}</strong><br>${esc(o.explanation)}</p>`).join('')}</details><div class="oral"><strong>Объясни своими словами</strong><p>${esc(c.oral)}</p><p class="small muted">Назови термин, покажи место в коде и приведи пример.</p></div></section>`;}
function quiz(){const s=state.session;if(!s)return home();const c=byId(s.deck[s.index]),a=s.answers[c.id],final=s.mode==='final';return `<div class="quiz-top"><span>${esc(topicName(c.topic))}</span><span>${final?'Тест':'Карточка'} ${s.index+1} из ${s.deck.length}</span></div>${progress(Object.keys(s.answers).length,s.deck.length,'Ответов в подходе')}<section class="question-sheet"><h1 id="question-heading" tabindex="-1">${esc(c.question)}</h1><p class="context">${final?'Объяснения появятся после завершения теста.':'Выбери один ответ. После ответа разберем причину и исходный код.'}</p><div class="answers">${s.orders[c.id].map((idx,pos)=>{const o=c.options[idx];const cls=a?(final?(a.choice===idx?'selected':''):o.correct?'correct':a.choice===idx?'incorrect':''):'';return `<button class="answer ${cls}" data-action="answer" data-choice="${idx}" ${a||busy||observer()?'disabled':''}><span class="number">${pos+1}</span><span>${esc(o.text)}${a?.choice===idx?'<span class="answer-label">Ваш ответ</span>':''}</span></button>`;}).join('')}</div>${a?(final?'<div class="notice info" role="status"><p>Ответ записан. Разбор будет после завершения теста.</p></div>':feedback(c,a)):''}</section><div class="actions quiz-actions">${button('next',s.index+1===s.deck.length?'Посмотреть результат':'Следующий вопрос','primary',`${!a||observer()?'disabled':''}`)}${button('home','К темам','quiet')}${button('finish',final?'Завершить досрочно':'Закончить подход','quiet',observer()?'disabled':'')}</div>`;}
function result(){const s=state.session;if(!s)return home();const answered=Object.keys(s.answers).length,correct=Object.values(s.answers).filter(a=>a.correct).length;return `<div class="intro"><h1>${s.mode==='final'?'Результат общего теста':'Подход завершен'}</h1><p>Проверь объяснения и проговори трудные ответы вслух.</p></div><p class="result-score">${correct}<small> из ${s.deck.length} верно</small></p><p class="muted">Отвечено: ${answered}. Без ответа: ${s.deck.length-answered}. ${s.mode==='final'?(correct===s.deck.length?'Все ответы верные. Теперь проверь устное объяснение.':'Ошибки снизили освоение. Вернись к карточкам перед следующей попыткой.'):'Верные ответы повышают уровень, ошибки возвращают вопросы на повторение.'}</p><div class="actions" style="margin-top:24px">${button('start','Новый подход','primary',observer()?'disabled':'')}${button('home','К темам')}</div><div class="program-head"><h2>Разбор ответов</h2></div>${s.deck.map(id=>{const c=byId(id),a=s.answers[id];return `<details class="review"><summary><span class="review-status ${a?.correct?'good':a?'bad':''}">${a?.correct?'Верно':a?'Повторить':'Без ответа'}</span>${esc(c.question)}</summary>${feedback(c,a,false)}</details>`;}).join('')}`;}
function stats(){const rows=bank.cards.filter(c=>state.levels[c.id]);return `<div class="intro"><h1>Прогресс подготовки</h1><p>${observer()?'Ответы Алексея на всех подключенных устройствах. Просмотр не меняет результат.':demo?'Это статистика отдельной пробной попытки в этом браузере.':'Здесь видно, что закрепилось и к чему нужно вернуться.'}</p></div><div class="stats-line"><span><strong>${mastered()}</strong> освоено</span><span><strong>${state.history.length}</strong> ответов в истории</span><span><strong>${state.finals.length}</strong> итоговых попыток</span></div>${!demo?button('refresh','Обновить прогресс'):''}${active()?`<div class="notice"><h3>Есть начатый ${state.session.mode==='final'?'тест':'подход'}</h3><p>Отвечено ${Object.keys(state.session.answers).length} из ${state.session.deck.length}.</p>${!observer()?button('resume','Продолжить','quiet'):''}</div>`:''}${rows.length?`<div class="table-wrap"><table><thead><tr><th>Вопрос</th><th>Уровень</th><th>Верно / ошибки</th><th>Последний ответ</th></tr></thead><tbody>${rows.sort((a,b)=>level(a.id)-level(b.id)).map(c=>{const p=state.levels[c.id];return `<tr><td>${esc(c.question)}</td><td>${p.level}/3</td><td>${p.correct} / ${p.wrong}</td><td>${date(p.lastAt)}</td></tr>`;}).join('')}</tbody></table></div>`:'<p class="empty">Пока нет ответов. После первого подхода здесь появятся результаты.</p>'}${state.finals.length?`<div class="program-head"><h2>Итоговые попытки</h2></div>${state.finals.map(f=>`<p>${date(f.at)}: ${f.correct} из ${f.total}, отвечено ${f.answered}. ${f.passed?'Все верно.':'Есть что повторить.'}</p>`).join('')}`:''}`;}
function library(){const cards=bank.cards.filter(c=>(filter==='all'||c.topic===filter)&&(!query||(c.question+' '+c.answer).toLowerCase().includes(query.toLowerCase())));return `<div class="intro"><h1>Все вопросы и объяснения</h1><p>Справочник для разбора с наставником. Чтение объяснений не повышает уровень освоения.</p></div><div class="filter"><input type="search" id="search" aria-label="Поиск вопроса" placeholder="Найти термин или вопрос" value="${esc(query)}"><select id="topic-filter" aria-label="Тема"><option value="all">Все темы</option>${bank.topics.map(t=>`<option value="${t.id}" ${t.id===filter?'selected':''}>${esc(t.title)}</option>`).join('')}</select></div><p class="small muted">Найдено: ${cards.length}</p>${cards.map(c=>`<details class="review"><summary>${esc(c.question)}</summary>${feedback(c,null,false)}</details>`).join('')}`;}
function rules(){return `<div class="intro"><h1>Как заниматься</h1><p>Цель - объяснить преподавателю работу программы, а не запомнить положение кнопки.</p></div><div class="rules"><article><h2>Один короткий подход</h2><p>До 15 вопросов. Когда уже есть пройденные карточки, в подход включаются 3-5 повторений. Сначала возвращаются слабые вопросы. Если новых карточек мало или нет, подход дополняется повторением.</p></article><article><h2>Как растет и уменьшается прогресс</h2><p>У каждого вопроса уровень от 0 до 3. Верный ответ в новом подходе дает +1. Ошибка отнимает 2, но уровень не падает ниже нуля. Уровень 3 означает освоение. Повторная ошибка на освоенном вопросе возвращает его к уровню 1.</p><p>Один вопрос встречается в подходе один раз. Повторный клик или перезагрузка не начисляют дополнительные баллы.</p></article><article><h2>Общее сохранение</h2><p>После подключения общего хранилища один код ученика открывает ту же попытку на телефоне и компьютере. Наставник использует отдельный код просмотра. При отсутствии связи ответ не считается сохраненным: сообщение на экране подскажет обновить состояние.</p><p>Пробный режим хранится только в этом браузере и не изменяет прогресс ученика.</p></article><article><h2>Общий тест</h2><p>Открывается, когда все ${bank.cards.length} вопросов имеют уровень 3. Вопросы перемешаны, объяснения скрыты до завершения. Итог «все верно» требует ответа на каждый вопрос без ошибки. Пропущенные вопросы не считаются правильными. Ошибочные ответы снижают освоение.</p></article><article><h2>Проверка понимания</h2><p>После ответа закрой варианты и произнеси объяснение своими словами. Найди функцию в коде. Затем ответь на дополнительный вопрос: что изменится, если убрать проверку или изменить порядок действий.</p></article><article><h2>Что именно изучаем</h2><p>Присланная версия сетевого калькулятора C++11 под Linux. В исходнике подтверждена ошибка индексов после accept. Карточки отдельно объясняют замысел и дефекты текущего кода. Презентация опирается на тот же банк.</p><a href="presentation.html">Перейти к презентации</a></article></div>`;}
function login(){return `<main id="main" class="main-wrap login"><h1>Подготовка к защите<br>сетевого калькулятора</h1><p class="muted">TCP, сокеты, poll и C++ на примере твоей программы. ${bank.cards.length} вопроса с подробным разбором.</p>${error?`<div class="notice error" role="alert">${esc(error)}</div>`:''}${cfg.sharedEnabled?`<form id="login-form"><label for="access-code">Код доступа ученика или наставника</label><input id="access-code" type="password" autocomplete="current-password" required placeholder="Введите выданный код"><button class="primary" ${busy?'disabled':''}>${busy?'Подключаем…':'Открыть общий прогресс'}</button><p class="small muted">Тот же код открывает тот же прогресс на другом устройстве.</p></form>`:'<div class="notice info"><p>Общее сохранение еще не подключено. Материалы доступны в пробном режиме с сохранением только в этом браузере.</p></div>'}<div class="actions">${button('demo','Открыть пробный режим')}</div><a class="document-link" href="presentation.html">Презентация для созвона</a></main>`;}
function render(focus=false){app.innerHTML=!state?login():shell(({home,quiz,result,stats,library,rules}[screen]||home)());if(focus){window.scrollTo({top:0});document.querySelector('#question-heading')?.focus({preventScroll:true});}}
async function request(path,payload){const r=await fetch(cfg.api+path,{method:payload?'POST':'GET',headers:{Authorization:'Bearer '+token,...(payload?{'Content-Type':'application/json'}:{})},...(payload?{body:JSON.stringify(payload)}:{}),cache:'no-store',signal:AbortSignal.timeout(12000)});let data;try{data=await r.json();}catch{throw Error('Сервер вернул непонятный ответ. Повторите позже.');}if(!r.ok){if(data.state)state=data.state;throw Error(data.error||'Сохранение недоступно.');}return data;}
async function refresh(){if(demo){error='';render();return;}busy=true;render();try{state=await request('/state');synced=true;error='';if(screen==='quiz'&&state.session?.finished)screen='result';}catch(e){error=e.message;synced=false;}finally{busy=false;render();}}
async function action(name,extra={}){if(busy||observer())return;busy=true;error='';render();const payload={...extra,revision:state.revision,sessionId:state.session?.id};try{if(demo){state=applyAction(bank,structuredClone(state),name,payload);localStorage.setItem(KEY,JSON.stringify(state));}else{state=await request('/'+name,payload);synced=true;}screen=state.session?.finished?'result':'quiz';}catch(e){error=e.message;synced=false;if(!demo){try{state=await request('/state');synced=true;}catch{}}}finally{busy=false;render(name==='next'||name==='start');}}
app.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;event.preventDefault();const a=el.dataset.action;
 if(['home','library','stats','rules'].includes(a)){screen=a;render(true);}
 else if(a==='demo'){demo=true;token='';error='';try{state=JSON.parse(localStorage.getItem(KEY))||emptyState();}catch{state=emptyState();}state.role='student';screen='home';render(true);}
 else if(a==='logout'){state=null;token='';demo=false;error='';localStorage.removeItem(TOKEN);render(true);}
 else if(a==='refresh')await refresh();
 else if(a==='resume'){screen=state.session?.finished?'result':'quiz';render(true);}
 else if(a==='start'||a==='topic'||a==='final')await action('start',{mode:a==='final'?'final':'cards',topic:el.dataset.topic||null});
 else if(a==='answer')await action('answer',{card:state.session.deck[state.session.index],choice:Number(el.dataset.choice)});
 else if(a==='next')await action('next');
 else if(a==='finish'){if(state.session.mode==='final'&&!confirm('Завершить тест? Неотвеченные вопросы останутся пропущенными, а ошибки снизят освоение.'))return;await action('finish');}
});
app.addEventListener('submit',async e=>{if(e.target.id!=='login-form')return;e.preventDefault();token=document.querySelector('#access-code').value.trim();busy=true;error='';render();try{state=await request('/state');localStorage.setItem(TOKEN,token);demo=false;synced=true;screen='home';}catch(e){error=e.message;token='';}finally{busy=false;render();}});
app.addEventListener('change',e=>{if(e.target.id==='topic-filter'){filter=e.target.value;render();}});
let searchTimer;app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const pos=document.querySelector('#search')?.selectionStart;render();const i=document.querySelector('#search');i?.focus();if(i&&pos!==undefined)i.setSelectionRange(pos,pos);},220);}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state&&!demo&&!busy)refresh();});
setInterval(()=>{if(state&&!demo&&!busy&&screen==='stats')refresh();},20000);
try{const response=await fetch('bank.json');if(!response.ok)throw Error('Не удалось загрузить вопросы.');bank=await response.json();try{token=cfg.sharedEnabled?localStorage.getItem(TOKEN)||'':'';}catch{}if(token){state=await request('/state');synced=true;}render();}catch(e){if(bank){error=e.message;token='';render();}else app.innerHTML=`<main class="loading"><h1>Материалы не загрузились</h1><p>${esc(e.message)}</p><button onclick="location.reload()">Повторить загрузку</button></main>`;}
